### ISSUE TITLE
discrepancy in output obtained from terraform_plan and terraform

### ISSUE THREAD

**Issue by yjhunjhunwala** [bridgecrewio/checkov#2092] opened 2021-12-13 11:32 UTC
when the azure_checkov.tf file is used the checks CKV2_AZURE_2,CKV2_AZURE_3,CKV2_AZURE_5 are marked as passed

whereas when plan file is created and scan is run the above checks are marked as failed (tf.json)

[New folder.zip](https://github.com/bridgecrewio/checkov/files/7703364/New.folder.zip
![tfoutput](https://user-images.githubusercontent.com/46134069/145804921-b8e47ce2-b126-49b2-b38a-f0018c4bba9f.JPG)
![planoutput](https://user-images.githubusercontent.com/46134069/145804927-d7c86a39-7858-4ef3-912f-af38c81d1ded.JPG)
)

**Comment by nimrodkor** [comment] 2021-12-13 11:50
Thanks for reporting @yashjhunjhunwala !
I believe this is a duplicate of #1469

**Comment by yjhunjhunwala** [comment] 2021-12-13 13:21
@nimrodkor Do we have any plan for fixing this ?

**Comment by nimrodkor** [comment] 2021-12-28 14:23
Closing to manage the conversation in a single issue

**Closed by nimrodkor** 2021-12-28 14:23 UTC
Labels: checks
