### ISSUE TITLE
git fatal: Could not read from remote repository when using private git repository for terraform modules

### ISSUE THREAD

**Issue by pandrel** [bridgecrewio/checkov#2136] opened 2021-12-21 22:16 UTC
**Describe the bug**
git fatal: Could not read from remote repository when using private git repository for terraform modules. 

**To Reproduce**

```terraform
module "sample_bucket" {
    source = "git::ssh://git@github.com/<<org>>>/<<repo>>//modules/s3-encrypted"

    bucket_name           = "sample-bucket"
    enable_lifecycle_rule = true
    enable_versioning     = true
    tags                  = local.default_tags

}
```
```
checkov -d . --download_external_modules True
```

```
2021-12-21 21:53:31,839 [MainThread  ] [WARNI]  Failed to download module git::ssh://git@github.com/<<org>>>/<<repo>>.git//modules/s3-encrypted:None
2021-12-21 21:53:31,916 [MainThread  ] [ERROR]  failed to get git::ssh://github.com/<<org>>>/<<repo>> because of Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --depth=1 ssh://github.com/<<org>>>/<<repo>> /home/ec2-user/environment/<<org>>>/<<repo>>/.external_modules/github.com/<<org>>>/<<repo>>/HEAD
  stderr: 'Cloning into '/home/ec2-user/environment/<<repo>>/.external_modules/github.com/<<org>>>/<<repo>>/HEAD'...
Permission denied (publickey).
fatal: Could not read from remote repository.
```

Error is due to the incorrect url being used in the git command.

git clone -v --depth=1 ssh://github.com/<<org>>>/<<repo>>

should be

git clone -v --depth=1 ssh://git@github.com/<<org>>>/<<repo>>

for some reason git@ is missing in newer releases (2.0.682). This issue was not identified in 2.0.540 release.

**Comment by gruebel** [comment] 2021-12-21 23:03
the bug is even a bit more specific, it only affects git URLs with sub directories in the source path.

**Comment by rotemavni** [comment] 2021-12-22 09:54
Hello @pandrel, thank you for bringing this issue to our attention.
I believe I found the cause to this issue, and it will be fixed in the following PR: https://github.com/bridgecrewio/checkov/pull/2138
How do you feel about this solution?

**Closed** 2021-12-22 11:02 UTC
Labels: bug, terraform
