### ISSUE TITLE
Checkov Action permissions defect probably related to recent dockerfile changes

### ISSUE THREAD

**Issue by njgibbon** [bridgecrewio/checkov#1503] opened 2021-08-16 22:01 UTC
**Describe the bug**
Hello,

Today the GitHub Action started showing a permissions issue. All working successfully until today. We are using the public github actions runners for this.

**Issue logs**
```
cp: can't create '/github/workspace/checkov-problem-matcher.json': Permission denied 
Error: Unable to process command '::add-matcher::checkov-problem-matcher.json' successfully. 
Error: Could not find file '/home/runner/work/<dir>/<dir>/checkov-problem-matcher.json'.
```

**Actions Config**
```
  checkov:
    runs-on: ubuntu-latest
    name: Checkov
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: modules/
          quiet: false
          soft_fail: false
          framework: terraform
          output_format: cli
```

Checkov does still run successfully and report results but this causes the action step to return a none zero exit code.

I've worked around very roughly by just shoving the json file into my root dir and moving on but just raising this issue to see if it is something which will affect others. I've not taken the time to replicate in other environments yet.

**EDIT**: I've just replicated the issue publicly here: https://github.com/njgibbon/test/actions

I think maybe there could be a good opportunity here for continuous testing of the action on goat or something like that.

It could be related to these changes: https://github.com/bridgecrewio/checkov/commit/ef302fbfe74732c5bdeb7c1d94c80fb9975089ad
https://github.com/bridgecrewio/checkov/commit/055815a146f4d8a907f5056a64d92c145fc5860c

And I suspect something to do with the permissions in the checkov container vs the github actions runner. Perhaps needs some trial and error to work out.

**Comment by nimrodkor** [comment] 2021-08-17 06:07
Hmmmm.
Might this get resolved in #1504 ?

**Comment by nimrodkor** [comment] 2021-08-17 07:43
You're right @njgibbon . I'm reverting that change for now, will revisit when I have more time

**Comment by mtcolman** [comment] 2021-08-23 09:25
Hi @nimrodkor I think you might be having issues related to this sorry saga: https://github.community/t/docker-action-cant-create-folder-in-runners-home-directory/17816/5.

The checkov [entrypoint.sh](https://github.com/bridgecrewio/checkov/blob/master/github_action_resources/entrypoint.sh) tries to do the following:
```
matcher_path=`pwd`/checkov-problem-matcher.json
warning_matcher_path=`pwd`/checkov-problem-matcher-softfail.json
cp /usr/local/lib/checkov-problem-matcher.json "$matcher_path"
cp /usr/local/lib/checkov-problem-matcher-softfail.json "$warning_matcher_path"
```

and the errors you are seeing are:
```
cp: can't create '/github/workspace/checkov-problem-matcher.json': Permission denied 
Error: Unable to process command '::add-matcher::checkov-problem-matcher.json' successfully. 
Error: Could not find file '/home/runner/work/<dir>/<dir>/checkov-problem-matcher.json'.
```

I believe the initial `cp /usr/local/lib/checkov-problem-matcher.json "$matcher_path"` doesn't happen (which is shown by the log event `cp: can't create '/github/workspace/checkov-problem-matcher.json': Permission denied`).

I believe the subsequent two error messages are as a result of that. I've had a look at the [github env variables](https://docs.github.com/en/actions/reference/environment-variables) and can see:
> GITHUB_WORKSPACE: The GitHub workspace directory path, initially empty. For example, /home/runner/work/my-repo-name/my-repo-name. The actions/checkout action will check out files, by default a copy of your repository, within this directory.

However there is no mention of `github/workspace` on the environment variables page.

**Comment by mtcolman** [comment] 2021-08-23 11:32
[This](https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions) is root cause of issue:

>USER
> Docker actions must be run by the default Docker user (root). Do not use the USER instruction in your Dockerfile, because you won't be able to access the GITHUB_WORKSPACE. For more information, see "Using environment variables" and USER reference in the Docker documentation.

In trials we have seen:
```
Run mtcolman/checkov-action@master
  with:
    quiet: false
    soft_fail: false
    framework: terraform
    output_format: cli
    directory: .
    log_level: WARNING
/usr/bin/docker run --name pandoraholladaycheckovpermissions1_9a83b7 --label c9e036 --workdir /github/workspace --rm -e INPUT_QUIET -e INPUT_SOFT_FAIL -e INPUT_FRAMEWORK -e INPUT_OUTPUT_FORMAT -e INPUT_DIRECTORY -e INPUT_CHECK -e INPUT_SKIP_CHECK -e INPUT_API-KEY -e INPUT_EXTERNAL_CHECKS_DIRS -e INPUT_EXTERNAL_CHECKS_REPOS -e INPUT_DOWNLOAD_EXTERNAL_MODULES -e INPUT_LOG_LEVEL -e INPUT_CONFIG_FILE -e INPUT_BASELINE -e INPUT_SOFT_FAIL_ON -e INPUT_HARD_FAIL_ON -e API_KEY_VARIABLE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/test/test":"/github/workspace" pandoraholladay/checkov-permissions:1  "." "" "" "false" "false" "terraform" "" "" "cli" "" "WARNING" "" "" "" ""

GitHub workspace is /github/workspace

total 24
drwxrwxr-x    1 checkov  root          4096 Aug 23 11:22 .
drwxr-xr-x    1 root     root          4096 Aug 23 11:22 ..
drwxr-xr-x    2 1001     121           4096 Aug 23 11:22 file_commands
drwxr-xr-x    2 1001     121           4096 Aug 23 11:22 home
drwxr-xr-x    2 1001     121           4096 Aug 23 11:22 workflow
drwxr-xr-x    4 1001     121           4096 Aug 23 11:22 workspace

id is uid=1000(checkov) gid=1000(checkov) groups=1000(checkov)

cp: can't create '/github/workspace/checkov-problem-matcher.json': Permission denied
Error: Unable to process command '::add-matcher::checkov-problem-matcher.json' successfully.
Error: Could not find file '/home/runner/work/test/test/checkov-problem-matcher.json'.
cp: can't create '/github/workspace/checkov-problem-matcher-softfail.json': Permission denied
```

Whereby the container mounts are performed by user=1001, group=121 and therefore the user in the container (checkov: uid=1000,gid=1000) can't access the directories.

**Closed** 2021-12-27 18:20 UTC
Labels: help wanted
