### ISSUE TITLE
CKV_K8S_40 check failing even when using a high UID

### ISSUE THREAD

**Issue by ajchiarello** [bridgecrewio/checkov#713] opened 2020-12-03 19:55 UTC
**Describe the bug**
When scanning my kubernetes YAML, it is failing the check even when the UID is set higher than 1000. It only passes when I set a UID higher than 10000. 

**To Reproduce**
Scan a YAML where the runAsUser is set to a high UID that is less than 10000.

**Expected behavior**
This check should pass

**Screenshots**
```
Check: CKV_K8S_40: "Containers should run as a high UID to avoid host conflict"
	FAILED for resource: Deployment.skunkworks.velero-testing
	File: /test-velero.yaml:1-29
	Guide: https://docs.bridgecrew.io/docs/bc_k8s_37
		1  | apiVersion: apps/v1
		2  | kind: Deployment
		3  | metadata:
		4  |   name: skunkworks
		5  |   namespace: velero-testing
		6  | spec: 
		7  |   replicas: 1
		8  |   revisionHistoryLimit: 0
		9  |   selector:
		10 |     matchLabels:
		11 |       app: velero-test
		12 |   template:
		13 |     metadata:
		14 |       labels:
		15 |         app: velero-test
		16 |     spec:
		17 |       containers:
		18 |       - name: xs-1
		19 |         image: alpine:3.12
		20 |         resources:
		21 |           requests:
		22 |             cpu: 10m
		23 |             memory: 16Mi
		24 |           limits:
		25 |             cpu: 10m
		26 |             memory: 16Mi
		27 |         securityContext:
		28 |           runAsUser: 1234
```
**Desktop (please complete the following information):**
 - Running in the bridgecrew/checkov:latest container

**Comment by metahertz** [comment] 2021-02-03 12:14
Hey @ajchiarello
A lot of linux distro's start regular system users from uid 1000, so 1000, 1001 would still conflict with the first two users is the logic here. 

Ie, ubuntu, my local SSH user:
`matt:x:1000:1000:Matt J:/home/matt:/bin/bash`

Any uid conflict would defeat the point of this check, although yes, annoying as most templated manifests seem to pick 1000!

**Comment by ajchiarello** [comment] 2021-02-03 14:06
Hey @metahertz - OK - but I was using 1234, and that triggered the alert. How high do I need to go with my yamls?

**Comment by scott-sudweeks** [comment] 2021-03-29 19:33
This got me too.

Per source code https://github.com/bridgecrewio/checkov/blob/25388a34231e09ac17b266ad9db0b4c0e806e956/checkov/kubernetes/checks/RootContainersHighUID.py#L97

The check is actually evaluating for >= 10,000.

I would suggest that the problem is with the messaging/documentation of CKV_K8S_40 indicating the value needs to be above 1,000.  The check and messaging should match as to not confuse users.

**Comment by metahertz** [comment] 2021-03-30 16:55
Thanks @scott-sudweeks, thats exactly the case, due to systems commonly starting non-root and non-system users at 1000+, so 10,000 seemed like a safe buffer.

Apologies @ajchiarello I didn't do a very good job of explaining that, we do indeed trigger on anything less than UID 10,000.

I've updated the documentation in the checkov guidance link for this check to reflect 10,000 and added more information on why!

**Comment by gruebel** [comment] 2021-12-10 18:24
Thanks @metahertz for adjusting the documentation! Since no further comments were added I'm closing this, but feel free to open a new issue, if further info are needed.

**Closed by gruebel** 2021-12-10 18:24 UTC
Labels: policy-discuss, More info required
