### ISSUE TITLE
error CKV2_DOCKER_1 when installing sudo

### ISSUE THREAD

**Issue by uwebartels** [bridgecrewio/checkov#5680] opened 2023-10-24 08:02 UTC
**Describe the issue**
checkov complains when installing sudo. I guess the check should warn about **using** sudo, not **installing** sudo.
Check ID: CKV2_DOCKER_1

**Examples**
The Dockerfile line 
`RUN apt-get update -y apt-get install -y --no-install-recommends openjdk-8-jdk ant ca-certificates-java sudo curl ...`
causes the error
`Check: CKV2_DOCKER_1: "Ensure that sudo isn't used"`

**Version (please complete the following information):**
 - checkov v2.4.48

**Additional context**
none.

If there is a workaround for this would be nice to know too.

Best...
Uwe

**Comment by gruebel** [comment] 2023-10-24 14:44
duplicate of #5578

**Closed by gruebel** 2023-10-24 14:44 UTC
Labels: checks
